name: AWS Terraform Workflow For Batch DevSecOps B49
on:
  # pull_request:
  #   types:
  #   - closed
  #   branches:
  #     - development
  #     - production
  #   paths-ignore:
  #     - 'Manual.yml'
  #     - 'ReadMe.md'
  push:
    branches:
      - development
      - production
    paths-ignore:
      - 'Manual.yml'
      - 'ReadMe.md'

#Use PR rather than push as most of the clients using PR for merging branches.

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: "us-east-1"
  ENV_DESTROY: "NO"
  TERRAFORM_DESTROY: ${{ vars.TERRAFORM_DESTROY}}
  TERRAFORM_VERSION: "1.14.0"

jobs:
  terraform-initiate:
    if: ${{ vars.TERRAFORM_DESTROY == 'NO' }}
    name: 'Stage_1 - Terraform Initialization'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dev-env
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: env.TERRAFORM_VERSION
      - name: Print Runner Hostname
        run: echo $HOSTNAME
      - name: Print Branch Name
        run: echo ${GITHUB_REF}
      - name: Terraform Version
        run: terraform version
      - name: Terraform Init, Format, Validate
        run: terraform init && terraform fmt && terraform get && terraform validate
      - name: Creating Terraform Workspaces
        run: |
          terraform workspace select dev || terraform workspace new dev
          terraform workspace select prod || terraform workspace new prod
          terraform workspace list
# Testing
  terraform-plan:
    if: ${{ vars.TERRAFORM_DESTROY == 'NO' }}
    name: 'Stage_3 - Terraform Plan'
    runs-on: ubuntu-latest
    needs: terraform-initiate
    defaults:
      run:
        working-directory: ./Alpha-Bravo
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: env.TERRAFORM_VERSION
      - name: Print Runner Hostname
        run: echo $HOSTNAME
      - name: Print Branch Name
        run: echo ${GITHUB_REF}
      - name: Terraform Version
        run: terraform version
      - name: Terraform Init, Format, Validate
        run: terraform init && terraform fmt && terraform get && terraform validate
      - name: Print Branch Reference
        run: echo The Current Branch Is $GITHUB_REF
      - name: Terraform Plan
        if: env.ENV_DESTROY == 'NO'
        run: |
          if [ ${GITHUB_REF} == 'refs/heads/development' ]; then
            echo "Running Terraform Plan For Development Environment"
            terraform workspace select dev
            terraform plan --var-file=Alpha.tfvars
          elif [ ${GITHUB_REF} == 'refs/heads/production' ]; then
            echo "Running Terraform Plan For Production Environment"
            terraform workspace select prod
            terraform plan --var-file=Bravo.tfvars
          else
            echo "Nothing Is Deployed As The Branch Is Not Dev OR Prod."
          fi